set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)

set(ENG_VALIDATION_LAYERS
    ON
    CACHE BOOL "Enable validation layers")
set(ENG_VALIDATION_LAYERS_GPU_ASSISTED
    OFF
    CACHE BOOL "Enable GPU assisted validation layers")
set(ENG_SHIPPING
    OFF
    CACHE BOOL "Install everything into the build directory")
set(ENG_WSI_SELECTION
    "XCB"
    CACHE STRING "Select WSI target (XCB, XLIB, WAYLAND, D2D)")
set(ENG_PLATFORM
    "VK_USE_PLATFORM_WIN32_KHR"
    CACHE STRING "Platform")

if(ANDROID)
  set(ENG_PLATFORM VK_USE_PLATFORM_ANDROID_KHR)
elseif(WIN32)
  set(ENG_PLATFORM VK_USE_PLATFORM_WIN32_KHR)
elseif(APPLE)
  set(ENG_PLATFORM VK_USE_PLATFORM_MACOS_MVK)
elseif(UNIX)
  set(ENG_PLATFORM VK_USE_PLATFORM_${ENG_WSI_SELECTION}_KHR)
endif()

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/engine/bin")

if(${ENG_PLATFORM} STREQUAL "VK_USE_PLATFORM_WIN32_KHR")
  if("${CMAKE_BUILD_TYPE}" STREQUAL "")
    set(ENG_BIN_DIRECTORY "${CMAKE_BINARY_DIR}/engine/bin/Debug" CACHE STRING "Executable directory")
  else()
    set(ENG_BIN_DIRECTORY "${CMAKE_BINARY_DIR}/engine/bin/${CMAKE_BUILD_TYPE}")
  endif()
endif()

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")

set(CMAKE_CXX_STANDARD 14)
